# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hound < Formula
  desc "Terminal UI for Solana — manage wallets, track portfolio, and swap tokens"
  homepage "https://github.com/dvrd/hound"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvrd/hound/releases/download/v1.0.0/hound_darwin_amd64.tar.gz"
      sha256 "1ea2546458af50071d1592c300a222ed9aa1a83a0f73e445967f04877d62ca93"

      define_method(:install) do
        bin.install "hound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvrd/hound/releases/download/v1.0.0/hound_darwin_arm64.tar.gz"
      sha256 "6db821f28179438c5c347fcc0be6ab5a718e79da4f0d991221a9a92c4ec6710d"

      define_method(:install) do
        bin.install "hound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvrd/hound/releases/download/v1.0.0/hound_linux_amd64.tar.gz"
      sha256 "2daa35a48086912497500f75fd0c6f9017642a1a81aef14ccede55cfa5996267"
      define_method(:install) do
        bin.install "hound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvrd/hound/releases/download/v1.0.0/hound_linux_arm64.tar.gz"
      sha256 "7f137860f2636577a9cf3ef25b9e20833888ed5a928909091b37a82d6402a647"
      define_method(:install) do
        bin.install "hound"
      end
    end
  end

  test do
    system "#{bin}/hound", "--version"
  end
end
