# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hound < Formula
  desc "Terminal UI for Solana — manage wallets, track portfolio, and swap tokens"
  homepage "https://github.com/dvrd/hound"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvrd/hound/releases/download/v1.1.0/hound_darwin_amd64.tar.gz"
      sha256 "35a154becbe0686096708eadbc0b9b452b352bc83566afab405fa4cb3514c0ee"

      define_method(:install) do
        bin.install "hound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvrd/hound/releases/download/v1.1.0/hound_darwin_arm64.tar.gz"
      sha256 "5a820d6dfc2abcddf50e33740d6d3bd45649ea3920e6c77d098744713f519de0"

      define_method(:install) do
        bin.install "hound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvrd/hound/releases/download/v1.1.0/hound_linux_amd64.tar.gz"
      sha256 "c8fbc91d1e1a5a4005a60836ea38619e004c1f32d533258629583d6125c3095c"
      define_method(:install) do
        bin.install "hound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvrd/hound/releases/download/v1.1.0/hound_linux_arm64.tar.gz"
      sha256 "d3f2d0ff492a452bc6de7ce48e979965443f12c67cae9d301cec6f96d2820157"
      define_method(:install) do
        bin.install "hound"
      end
    end
  end

  test do
    system "#{bin}/hound", "--version"
  end
end
