# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hound < Formula
  desc "Terminal UI for Solana — manage wallets, track portfolio, and swap tokens"
  homepage "https://github.com/dvrd/hound"
  version "0.23.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvrd/hound/releases/download/v0.23.1/hound_darwin_amd64.tar.gz"
      sha256 "e75b372e2bfaab4b08014396d7c160bb8c62ad845fd75cb072c2beeb279c5ec1"

      define_method(:install) do
        bin.install "hound"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvrd/hound/releases/download/v0.23.1/hound_darwin_arm64.tar.gz"
      sha256 "5442418f47ebbd15fe99cecc76a6755b9c59be815cbf54483a1bf2d3d42162ab"

      define_method(:install) do
        bin.install "hound"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvrd/hound/releases/download/v0.23.1/hound_linux_amd64.tar.gz"
      sha256 "957142dc07078968300d17da192a06e292361ee828cd343d61a5cb5ccaef058a"
      define_method(:install) do
        bin.install "hound"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvrd/hound/releases/download/v0.23.1/hound_linux_arm64.tar.gz"
      sha256 "2b2e5d4f0f5abd8a768f1bfeb4d6db63b18e23f02be1d5f5a38c0ba463644244"
      define_method(:install) do
        bin.install "hound"
      end
    end
  end

  test do
    system "#{bin}/hound", "--version"
  end
end
